In [2]:
import numpy as np

In [40]:
# Bin Wang Data
a = 100;
b = 10;
k = 1e-13;
mu_f =1e-3;
F = 5.94e8;
E = 5.94e9;
nu = 0.2;
alpha = 1;
c_0 = 1 / 1.65e10;


In [15]:
# Phillips Phillips Data
a = 1;
b = 1;
k = 1e-2;
mu_f =1;
F = 2e3;
E = 1e4;
nu = 0.2;
alpha = 0.75;
c_0 = 1e-4;

In [16]:
lame_lambda = E * nu / (1 + nu) / (1 - 2 * nu);
lame_mu = E / 2 / (1 + nu);
K_bulk = lame_lambda + 2. / 3 * lame_mu;
K_u = K_bulk + alpha * alpha / c_0;

In [18]:
M = K_bulk/(1-alpha)/(alpha - 0.2)
M

40404.0404040404

In [21]:
K_dr = 0.5 + 2./3 * 0.125
K_dr/(1-0.75)/(0.75-0.2)

4.242424242424242

In [22]:
28/3

9.333333333333334

In [12]:
K_bulk

5555.555555555556

In [13]:
K_u

15555.555555555555

In [80]:
c_f = 1. / c_0 * k/mu_f * (K_bulk + 4. / 3 * lame_mu) / (K_u + 4. / 3 * lame_mu);

In [81]:
B = alpha / c_0 / K_u

In [82]:
B

0.6428571428571429

In [83]:
nu_u=(3*nu + alpha* B *(1-2*nu))/(3-alpha*B*(1-2*nu))

In [84]:
lame_lambda

2777.777777777778

In [85]:
lame_mu

4166.666666666667

In [86]:
K_bulk

5555.555555555556

In [87]:
alpha*alpha/K_bulk/c_0

1.7999999999999998

In [88]:
F*B*(1+nu_u)/3/a

590.1639344262295

In [89]:
cc = (1 - nu) / (nu_u - nu)

In [90]:
nu_u

0.3770491803278689

In [91]:
cc

4.518518518518518

# Rate of Convergence

In [8]:
e_p_l2= np.array([5.8593e+01, 2.5606e+01, 5.7682e+00, 3.5995e+00])

In [9]:
h = 1.0/np.array([16, 32, 64, 128])

In [10]:
np.polyfit(np.log(h),np.log(e_p_l2),1)

array([1.42248685, 8.00960936])

In [18]:
rate =[]
for i in range(1, len(h)):
    print(h[0:i+1])
    rate.append(np.polyfit(np.log(h[0:i+1]),np.log(e_p_l2[0:i+1]),1))
rate

[0.0625  0.03125]
[0.0625   0.03125  0.015625]
[0.0625    0.03125   0.015625  0.0078125]


[array([1.19424642, 7.38176938]),
 array([1.67226761, 8.81757191]),
 array([1.42248685, 8.00960936])]

In [16]:
1/16

0.0625

In [19]:
e_u_energy = np.array([3.5313e+01, 2.9214e+01, 1.5817e+01, 8.2028e+00 ])

In [20]:
rate_u =[]
for i in range(1, len(h)):
    rate_u.append(np.polyfit(np.log(h[0:i+1]),np.log(e_u_energy[0:i+1]),1))
rate_u

[array([0.27353948, 4.32266365]),
 array([0.5793617 , 5.24124282]),
 array([0.7203217 , 5.69720428])]

In [23]:
eta_flow = np.array([4.333048e-13, 2.605864e-13, 1.416431e-13])
eta_jump = np.array([5.671967e+12, 1.595890e+10, 5.053557e+08])
h1= 1.0/np.array([32, 64, 128])
# convergence of eta_flow
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_flow[0:i+1]),1))

[  0.73362043 -25.92480034]
[  0.80656095 -25.65515492]


In [24]:
# convergence of eta_jump
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_jump[0:i+1]),1))

[ 8.47334411 58.73293   ]
[ 6.72713116 52.2775562 ]


In [25]:
eta_partial_sigma = np.array([3.135475e+13, 2.544001e+13, 1.809411e+13])
eta_sigma = np.array([2.019717e+13, 7.616620e+12, 2.317102e+12])
eta_partial_u = np.array([2.477221e+15, 1.496559e+15, 8.401565e+14])
eta_u = np.array([2.230781e+14, 5.567158e+13, 1.390609e+13])

In [26]:
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_partial_sigma[0:i+1]),1))

[ 0.30158478 32.12160008]
[ 0.39658193 32.47278414]


In [27]:
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_sigma[0:i+1]),1))

[ 1.40693033 35.51261258]
[ 1.56187985 36.08542762]


In [28]:
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_partial_u[0:i+1]),1))

[ 0.72707342 37.96575823]
[ 0.77999629 38.1614027 ]


In [29]:
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_u[0:i+1]),1))

[ 2.00253595 39.97880381]
[ 2.00188008 39.97637916]


In [30]:
eta_tot =np.array([5.247337e+07, 3.982252e+07, 2.957833e+07])
error = np.array([8.161212e+03, 7.448150e+03, 6.327309e+03])

In [31]:
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(eta_tot[0:i+1]),1))

[ 0.39800093 19.15518247]
[ 0.41352242 19.2125621 ]


In [32]:
for i in range(1, len(h1)):
    print(np.polyfit(np.log(h1[0:i+1]),np.log(error[0:i+1]),1))

[0.13190129 9.46428301]
[0.18359568 9.65538606]


## A second groups of test

In [33]:
e_l2_p = np.array([3.3728e-02, 4.3889e-03, 2.3790e-03])
e_u_enery = np.array([3.0533e-02, 1.3173e-02, 6.6013e-03])
h = 1./np.array([16, 32, 64])

In [35]:
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(e_l2_p[0:i+1]),1))

[2.94201547 4.76757198]
[1.9127598  1.67606076]


In [46]:
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(e_u_energy[0:i+1]),1))

[0.27353948 4.32266365]
[0.5793617  5.24124282]


In [37]:
eta_flow = np.array([6.1444e-02, 2.8578e-02, 1.2134e-02])

In [38]:
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_flow[0:i+1]),1))

[1.10436718 0.27232691]
[1.17010846 0.46978989]


In [39]:
eta_jump = np.array([1.2706e+00, 1.2016e-01, 2.0064e-02])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_jump[0:i+1]),1))

[3.4024813  9.67317051]
[2.99237843 8.44137004]


In [40]:
eta_partial_sigma = np.array([ 1.2082e+05, 6.1742e+04, 2.7387e+04])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_partial_sigma[0:i+1]),1))

[ 0.96853517 14.3874068 ]
[ 1.07064807 14.69411698]


In [41]:
eta_sigma = np.array([1.3898e+03 , 3.4954e+02, 8.8761e+01])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_sigma[0:i+1]),1))

[ 1.99134782 12.75810364]
[ 1.98440378 12.73724625]


In [42]:
eta_partial_u = np.array([5.8251e+05, 2.3059e+05, 7.1554e+04])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_partial_u[0:i+1]),1))

[ 1.33695287 16.98192208]
[ 1.51258925 17.50947014]


In [43]:
eta_u =np.array([1.4929e+03, 3.6203e+02, 9.0312e+01])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_u[0:i+1]),1))

[ 2.04393637 12.97547076]
[ 2.02352801 12.91417143]


In [44]:
eta_tot = np.array([8.4037e+02, 5.4132e+02, 3.1483e+02])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_tot[0:i+1]),1))

[0.63454297 8.49316895]
[0.70822582 8.71448555]


In [45]:
error = np.array([4.0870e-02, 1.3498e-02, 6.7801e-03])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(error[0:i+1]),1))

[1.59829658 1.2340601 ]
[1.29583189 0.32556573]


# Third groups of tests
time interval [0.01,0.0101] with $\Delta t = $1e-6

In [10]:
e_l2_p = np.array([4.0447e-04, 1.0507e-04, 3.4714e-05, 1.5875e-05])
e_u_energy = np.array([ 1.2873e-02 , 6.4361e-03 , 3.2180e-03, 1.6090e-03 ])
h = 1./np.array([32, 64, 128,258])

In [11]:
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(e_l2_p[0:i+1]),1))

[ 1.9446819  -1.07317912]
[ 1.77122159 -1.71442457]
[ 1.5554166  -2.56234911]


In [12]:
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(e_u_energy[0:i+1]),1))

[ 1.00008966 -0.88657654]
[ 1.00005604 -0.88670084]
[ 0.99667134 -0.89999973]


In [13]:
eta_alg = np.array([4.6588e-08,  1.1297e-08,  4.2233e-09 ,2.4755e-09])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_alg[0:i+1]),1))

[ 2.04401869 -9.79789387]
[  1.73175788 -10.95225495]
[  1.40673579 -12.22930699]


In [14]:
eta_flow = np.array([4.2977e-06, 1.0926e-06, 2.7545e-07, 6.9153e-08])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_flow[0:i+1]),1))

[ 1.97579945 -5.50983147]
[ 1.98185121 -5.48745943]
[ 1.97940659 -5.49706465]


In [15]:
eta_jump = np.array([1.2880e-05, 1.7173e-06, 2.8739e-07,  7.3336e-08])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_jump[0:i+1]),1))

[ 2.9069186  -1.18522268]
[ 2.74298946 -1.79123346]
[ 2.48587764 -2.80145764]


In [16]:
eta_partial_sigma = np.array([ 1.9216e-02, 4.8855e-03, 1.2314e-03, 3.0911e-04])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_partial_sigma[0:i+1]),1))

[1.97572993 2.89534614]
[1.98196834 2.91840819]
[1.97956096 2.90894932]


In [17]:
eta_sigma = np.array([3.4125e+02, 8.6856e+01,  2.1905e+01 ,  5.5000e+00 ])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_sigma[0:i+1]),1))

[ 1.97413163 12.6744342 ]
[ 1.98074846 12.69889522]
[ 1.97864349 12.69062454]


In [18]:
eta_partial_u = np.array([2.0138e-02, 4.9894e-03, 1.2431e-03, 3.1049e-04 ])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_partial_u[0:i+1]),1))

[2.01298217 3.07131788]
[2.00895307 3.05642317]
[1.99950555 3.0193027 ]


In [19]:
eta_u =np.array([3.5345e+02, 8.8375e+01, 2.2094e+01 , 5.5236e+00 ])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_u[0:i+1]),1))

[ 1.99979593 12.79850657]
[ 1.9998898  12.79885361]
[ 1.99319603 12.77255295]


In [20]:
eta_tot = np.array([2.635789e+01, 1.323787e+01, 6.633386e+00, 3.320270e+00])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(eta_tot[0:i+1]),1))

[0.99356388 6.71519766]
[0.99520875 6.7212784 ]
[0.99299456 6.71257858]


In [21]:
error = np.array([1.323499e-02, 6.619421e-03, 3.312303e-03, 1.658809e-03  ])
for i in range(1, len(h)):
    print(np.polyfit(np.log(h[0:i+1]),np.log(error[0:i+1]),1))

[ 0.99958017 -0.86061032]
[ 0.99922527 -0.86192229]
[ 0.99536708 -0.87708163]


# Convergence under time refinement
Time interval [0.01, 0.02], mesh 256x256

In [1]:
t=np.array([1e-3,5e-4,2e-4,1e-4])

NameError: name 'np' is not defined

In [5]:
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(e_l2_p[0:i+1]),1))

[0.96421933 3.42923781]
[0.96832564 3.45863581]
[0.96665213 3.44626477]


In [6]:
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(e_u_energy[0:i+1]),1))

[0.96234101 2.67089463]
[0.96211057 2.66924486]
[0.95148205 2.59067627]


In [8]:
eta_time = np.array([1.3245e-02, 3.4357e-03, 5.6230e-04, 1.4166e-04 ])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_time[0:i+1]),1))

[1.94677187 9.12368851]
[1.96365046 9.24452602]
[1.97141798 9.30194537]


In [9]:
eta_tot = np.array([4.5920e-02, 2.3467e-02, 9.8965e-03,  5.5714e-03 ])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_tot[0:i+1]),1))

[0.96848922 3.609232  ]
[0.95298497 3.49823369]
[0.91962682 3.25164207]


# Convergence under simutaneously space and time refinement

In [6]:
e_l2_p = np.array([4.0527e-02,  2.0760e-02, 1.0508e-02, 5.2867e-03])
e_u_energy = np.array([1.9748e-02, 1.0104e-02, 5.1113e-03, 2.5708e-03])
t = np.array([1e-3, 5e-4, 2.5e-4, 1.25e-4])

In [7]:
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(e_l2_p[0:i+1]),1))

[0.96507694 3.46072847]
[0.97369764 3.52226995]
[0.97976504 3.5669858 ]


In [8]:
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(e_u_energy[0:i+1]),1))

[0.96678001 2.75357663]
[0.97497219 2.81205901]
[0.98074162 2.85457886]


In [9]:
eta_time = np.array([1.3215e-02, 3.4323e-03, 8.7498e-04, 2.2091e-04])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_time[0:i+1]),1))

[1.94492886 9.10868989]
[1.95839129 9.2047955 ]
[1.96795754 9.27529736]


In [10]:
eta_flow = np.array([ 1.7039e-04, 4.4629e-05, 1.1422e-05, 2.8891e-06])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_flow[0:i+1]),1))

[1.93278728 4.67380092]
[1.94947674 4.79294367]
[1.96123963 4.8796345 ]


In [11]:
eta_jump = np.array([2.6802e-05, 9.7493e-06, 4.3753e-06, 2.1219e-06])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_jump[0:i+1]),1))

[ 1.45897012 -0.44882551]
[ 1.30744341 -1.53054505]
[ 1.2132653  -2.22462393]


In [12]:
eta_partial_sigma = np.array([6.9317e+01, 1.8223e+01, 4.6724e+00, 1.1830e+00])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_partial_sigma[0:i+1]),1))

[ 1.92744873 17.55303434]
[ 1.94548676 17.68180431]
[ 1.95815865 17.77519427]


In [13]:
eta_E_sigma = np.array([ 5.2784e+01, 1.2049e+01, 2.8727e+00 ,  7.0101e-01])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_E_sigma[0:i+1]),1))

[ 2.13118727 18.68792821]
[ 2.09981072 18.46393718]
[ 2.07719997 18.29729928]


In [14]:
eta_partial_u = np.array([ 7.1801e+01, 1.8542e+01, 4.7128e+00, 1.1881e+00])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_partial_u[0:i+1]),1))

[ 1.95320707 17.76617486]
[ 1.96467379 17.8480335 ]
[ 1.97279678 17.90789876]


In [15]:
eta_E_u = np.array([5.4670e+01, 1.2259e+01, 2.8975e+00, 7.0402e-01 ])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_E_u[0:i+1]),1))

[ 2.15690808 18.90070826]
[ 2.1189344  18.62962165]
[ 2.09179282 18.42959214]


In [16]:
eta_tot = np.array([1.5767e+01,  7.8151e+00, 3.8931e+00, 1.9433e+00])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(eta_tot[0:i+1]),1))

[1.01257194 9.75251834]
[1.00895844 9.72672223]
[1.00663279 9.70958251]


In [17]:
error = np.array([5.0968e-02, 2.5947e-02 , 1.3115e-02, 6.6144e-03])
for i in range(1, len(t)):
    print(np.polyfit(np.log(t[0:i+1]),np.log(error[0:i+1]),1))

[0.974024   3.75176213]
[0.97918697 3.78861955]
[0.98220786 3.81088306]
